name: Playwright E2E tests

on:
  push:
    branches: [main, playwright-spike]
  pull_request:
    branches: [main]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: '14.19.1'

      - name: Check out repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          path: ./ussf-portal-cms

      - name: Check out portal client
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: USSF-ORBIT/ussf-portal-client
          path: ./ussf-portal-client

      - name: Build image for testing
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $IMAGE_TAG --target e2e .
        working-directory: ./ussf-portal-cms

      - name: Docker compose
        run: docker-compose -f docker-compose.e2e.yml up -d
        working-directory: ./ussf-portal-cms
        env:
          IMAGE_TAG: ${{ github.sha }}

      - name: Install deps
        run: yarn e2e:install
        working-directory: ./ussf-portal-cms

      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: ./ussf-portal-cms/e2e

      - name: Run e2e tests
        run: yarn e2e:test
        working-directory: ./ussf-portal-cms

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        with:
          name: playwright-results
          path: ussf-portal-cms/e2e/test-results
