on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29 # v3
        with:
          release-type: node
          package-name: ussf-portal-cms
          include-v-in-tag: false
          changelog-types: >
            { "types":
              [
                { "type": "build", "hidden": true },
                { "type": "chore", "hidden": true },
                { "type": "ci", "hidden": true },
                { "type": "dev", "hidden": true },
                { "type": "feat", "section": "Features" },
                { "type": "fix", "section": "Bug Fixes" },
                { "type": "perf", "section": "Performance Improvements" },
                { "type": "refactor", "hidden": true },
                { "type": "revert", "section": "Reverted Changes" },
                { "type": "style", "hidden": true },
                { "type": "test", "hidden": true },
                { "type": "docs", "section": "Documentation" },
                { "type": "security", "section": "Security Improvements" }
              ]
            }
